In [ ]:
#1. 导入numpy库并简写为 np
import numpy as np

In [5]:
#2. 打印numpy的版本和配置说明
import numpy as np
np.__version__, np.show_config

('1.19.2', <function numpy.__config__.show()>)

In [9]:
#3. 创建一个长度为10的空向量
np.empty(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
#4. 如何找到任何一个数组的内存大小？
a = np.zeros(10, dtype=int)
a.size*a.itemsize

80

In [14]:
#5. 如何从命令行得到numpy中add函数的说明文档?
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
#6. 创建一个长度为10并且除了第五个值为1的空向量
a = numpy.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [16]:
# 7. 创建一个值域范围从10到49的向量
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
#8. 反转一个向量(第一个元素变为最后一个)
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
#9. 创建一个 3x3 并且值从0到8的矩阵
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
a = np.array([1,2,0,0,4,0])
[i for i in range(a.size) if a[i] != 0]
np.nonzero(a)  #标答，直接用库函数

(array([0, 1, 4]),)

In [32]:
#11. 创建一个 3x3 的单位矩阵
np.eye(3, 3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
#12. 创建一个 3x3x3的随机数组
np.random.random((3, 3, 3))

array([[[0.06234134, 0.16885947, 0.72423544],
        [0.09062648, 0.05516739, 0.14137174],
        [0.11923178, 0.31751636, 0.86396323]],

       [[0.55378969, 0.1028063 , 0.20685195],
        [0.40757118, 0.12046233, 0.21775027],
        [0.86272695, 0.26457044, 0.06728131]],

       [[0.4494721 , 0.89643783, 0.02635102],
        [0.95867979, 0.70254885, 0.68842449],
        [0.27647822, 0.48715406, 0.35473173]]])

In [42]:
#13. 创建一个 10x10 的随机数组并找到它的最大值和最小值
a = np.random.random((10,10))
a.max(), a.min()

(0.9848386691838211, 0.0028016005216909834)

In [45]:
#14. 创建一个长度为30的随机向量并找到它的平均值
a = np.random.random(30)
a, a.mean()

(array([0.39492254, 0.07827017, 0.99188944, 0.90014544, 0.99395477,
        0.69071381, 0.46222845, 0.32750595, 0.41525919, 0.2353351 ,
        0.28007314, 0.98555931, 0.96755193, 0.06566871, 0.75843526,
        0.00700746, 0.24206484, 0.56143129, 0.00256263, 0.95561459,
        0.4898838 , 0.95849945, 0.48483524, 0.56951546, 0.23008305,
        0.12943868, 0.62091672, 0.52930438, 0.25461754, 0.01046351]),
 0.4864583959865598)

In [50]:
#15. 创建一二维数组，其中边界值为1，其余值为0
a = np.ones((10,10))
a[1:-1, 1:-1] = 0  #不要被二维数组的思想限制 a[1:-1][1:-1]
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
#16. 对于一个存在在数组，如何添加一个用0填充的边界?
np.info(np.pad)
np.pad(a, pad_width=1, mode='constant', constant_values=0)

 pad(*args, **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
# 17. 以下表达式运行的结果分别是什么?
0*np.nan # nan=not a number
np.nan == np.nan 
np.inf > np.nan #inf = infinity(无穷)
np.nan - np.nan
np.inf - np.inf
np.nan - np.inf
np.inf - np.nan
0.3 == 0.1*3
0.1*3

0.30000000000000004

In [74]:
#18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
np.info(np.diag) #np.diag 对角线
np.diag(1+np.arange(4), k=-1)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [77]:
#19. 创建一个8x8 的矩阵，并且设置成棋盘样式(0,1交错)
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [84]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
a = np.arange(6*7*8).reshape(6,7,8) #get_index 之类的库函数
np.unravel_index(100, (6,7,8))  #只要获得索引即可

(1, 5, 4)

In [87]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
np.info(np.tile) #类似元素复制
np.tile(np.array([[1,0],[0,1]]), (4,4))

 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [91]:
#22. 对一个5x5的随机矩阵做归一化 归一化：(x-min(x)) / (max(x) - min(x))
a = np.random.random((5,5)) #
(a-np.min(a)) / (np.max(a)-np.min(a))

array([[0.29986267, 1.        , 0.17729833, 0.69775625, 0.53634192],
       [0.2896906 , 0.10086583, 0.39966025, 0.        , 0.66602426],
       [0.75553531, 0.73587903, 0.44108142, 0.76522816, 0.42248458],
       [0.68229473, 0.02430185, 0.3006835 , 0.85852683, 0.82764899],
       [0.69330128, 0.71347556, 0.94455922, 0.20663233, 0.33954588]])

In [93]:
#23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
numpy.info(numpy.dtype)
np.dtype([("r",np.ubyte,1), ("g",np.ubyte,1), ("b",np.ubyte,1), ("a",np.ubyte,1)])  #不是很懂？

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

/usr/local/python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  app.launch_new_instance()


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [95]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
np.dot(a,b) #矩阵相乘

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [98]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反
a = np.arange(10)
a[(a>3) & (a<8)] *= -1   ##可以在里面用lambda的判断用法？强！
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [102]:
# 26. 下面脚本运行后的结果是什么?
sum(range(5), -1)  #[0,1,2,3,4] + -1
np.info(np.sum)
np.sum(range(5), -1) #这里的-1指的是axis=-1 默认所有轴，所以为[0,1,2,3,4]的和

 sum(*args, **kwargs)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same precision as the platform integer is used.
out : ndarray, optional


10

In [112]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个?
a = np.arange(3) #[0,1,2]
a**a
2 << a >> 2 #legal ,答案错误？ 移位操作 
a < -a
1J*a 
a/1/1
#a<a>a  #不合法

array([0., 1., 2.])

In [115]:
# 28. 下列表达式的结果分别是什么?
np.array(0) /np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app
/usr/local/python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  app.launch_new_instance()


array([-9.22337204e+18])

In [116]:
# 29. 如何从零位对浮点数组做舍入 ?
a = np.random.random(10)
np.ceil(a)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
# 30. 如何找到两个数组中的共同元素?
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
print(a, b)
np.intersect1d(a, b) # intersect1d取重复元素

[1 3 0 9 3 6 6 8 2 5] [6 2 0 4 2 2 7 8 3 8]


array([0, 2, 3, 6, 8])

In [126]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
np.seterr(all='ignore')
np.ones(1)/0

array([inf])

In [129]:
# 32. 下面的表达式是正确的吗?
np.sqrt(-1) ==np.emath.sqrt(-1)  #flase
np.sqrt(-1)   #not a number
np.emath.sqrt(-1) # 可以共轭负数

1j

In [135]:
# 33. 如何得到昨天，今天，明天的日期?
#np.info(np.datetime64)
np.datetime64('today', 'D')
np.datetime64('1', 'D')

numpy.datetime64('0001-01-01')

In [137]:
# 34. 如何得到所有与2016年7月对应的日期？
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]') #dtype 输出格式 arange还可以输出一段日期

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [142]:
# 35. 如何直接在位计算(A+B)*(-A/2)(不建立副本)?
# 利用 np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=) 在原位置进行计算
a = np.ones(3) * 1
b = np.ones(3) * 2
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)

array([-1.5, -1.5, -1.5])

In [152]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分
a = np.random.uniform(0,10,10)
a - a % 1 # % 取余
np.floor(a) # floor向下取整
np.ceil(a) -1 # ceil向上取整
a.astype(int) # 类型强转
np.trunc(a) 
np.info(np.trunc)

trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the truncated value of the input, element-wise.

The truncated value of the scalar `x` is the nearest integer `i` which
is closer to zero than `x` is. In short, the fractional part of the
signed number `x` is discarded.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninit

In [156]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
a = np.zeros((5,5))
a += np.arange(5)   #可以每一行都加
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [158]:
# 38. 使用生成器创建一个大小为10的数组
def gen(num):
    for i in range(num):
        yield i
    return i
np.array([i for i in gen(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
# 39. 创建一个大小为10的数组，值为0到1之间，不包含0和1
np.info(np.linspace)
np.linspace(0, 1, 11, False)[1:] #创建一组步长为x的数

 linspace(*args, **kwargs)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dty

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [164]:
# 40.创建一个大小为10的数组并排序
a = np.random.randint(0, 9, 10) # 0-9 的十个数
np.sort(a)

array([0, 1, 2, 4, 5, 5, 6, 6, 8, 8])

In [ ]:
https://zhuanlan.zhihu.com/p/58576235