### 1. 概述
#### 1.1 基本概念
+ 主要对象为**同种元素**的多维数组
+ 在Numpy中维度（dimensions）叫做轴（axes），轴的个数叫做秩
    + 维度/轴：相当于层
    + 秩：相当于层数
    + 维度长度：该层元素个数
    
  ```
  [[1,0,0],[0,1,2]] #2x3的数组  秩：2（即有2层） 第一个维度长度为2，第二个维度长度为3
  ```
#### 1.2 标准函数
+ Numpy的数组类被称为ndarry 对象的属性有:

In [28]:
from numpy import *
import array
ary = array.array('i',range(15))
print(ary) 
print(type(ary)) # 类型为array.array
test = arange(15).reshape((3,5))
print(type(test)) #类型为numpy.ndarray
print(test)
print(test.shape) # (3,5) 3x5的数组
print(test.ndim) # 2  数组的维数
print(test.dtype.name) # int64 描述数组中元素的类型
print(test.itemsize) #数组中每个元素字节的大小
print(test.size) #数组所有元素的个数

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
<class 'array.array'>
<class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15


### 2. 数组的基本操作
#### 2.1 数组的创建
+ 使用array函数从常规的Python列表和元组创建 可以通过dtype指定数据类型

In [39]:
from numpy import *
a_from_l = array([1,2,3]) #从常规的Python列表
print(type(a_from_l),a_from_l)
a_from_t = array((1,2,3)) #从常规的Python元组
print(type(a_from_t),a_from_t)


#多维
a_complex = array([[1,2,3],[4,5,6]])
print(a_complex, a_complex.size, a_complex.ndim)
b_complex = array(((1,2,3),(4,5,6)))
print(b_complex, b_complex.size, b_complex.ndim)

<class 'numpy.ndarray'> [1 2 3]
<class 'numpy.ndarray'> [1 2 3]
[[1 2 3]
 [4 5 6]] 6 2
[[1 2 3]
 [4 5 6]] 6 2


+ numpy提供类似range 函数 arange返回函数列表 

In [44]:
from numpy import arange
ar = arange(4,8,2)
print(ar, type(ar))

[4 6] <class 'numpy.ndarray'>


#### 2.2 打印数组
+ 以嵌套的形式打印，数组太大时会自动省略中间元素而只打印最后元素（可以通过禁用该属性来强制打印set_printoptions(threshold='nan')）

In [48]:
print(arange(12).reshape(3,4))
print(arange(10000).reshape(100,100)) #大数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#### 2.3 基本运算
+ 算术运算：所有元素进行运算
+ 计算矩阵乘法：使用dot
+ 用axis=0 来只计算列，axis=1来只计算行

In [64]:
a_suan = arange(6).reshape(2,3)
b_suan = array([(2,3,4),(5,4,3)])
print(a_suan - b_suan)
print(b_suan*2, b_suan**2) #**2 为平方
print(b_suan * sin(a_suan))
print(a_suan < 2)
print(dot(a_suan, arange(6).reshape(3,2))) # 2x3 * 3x2 = 2x2

[[-2 -2 -2]
 [-2  0  2]]
[[ 4  6  8]
 [10  8  6]] [[ 4  9 16]
 [25 16  9]]
[[ 0.          2.52441295  3.63718971]
 [ 0.70560004 -3.02720998 -2.87677282]]
[[ True  True False]
 [False False False]]
[[10 13]
 [28 40]]


In [78]:
###　常用方法
print(a_suan, a_suan.min(), a_suan.max()) #所有元素最小值,最大值
print(a_suan.sum()) #所有元素的和
print(exp(a_suan)) #取e^x
print(a_suan.sum(axis=0), a_suan.sum(axis=1)) 
print(a_suan.min(axis=0), a_suan.min(axis=1)) # axis=0 指定列 axis=1 指定行 

[[0 1 2]
 [3 4 5]] 0 5
15
[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]
[3 5 7] [ 3 12]
[0 1 2] [0 3]


### 3. 通用函数ufunc
+ 基本通用函数：arange()、exp()...
+ 索引、切片和迭代（可以理解为numpy中的array[list格式可以不唯一]）
    + 多维数组可以使用逗号分隔（list无法如此使用,类似latax的用法）
    + 当少于维度的索引被提供时，缺失的索引默认为整个切片 eg: a[-1] == a[-1,:]
    + 点(...)代表许多产生一个完整的索引元组必要的分号

In [10]:
from numpy import *
a_ufunc = arange(3)
print(a_ufunc, exp(a_ufunc))  # e^x
print(sqrt(a_ufunc)) #开方

## 多维数组使用逗号分隔
a_ufunc = arange(9).reshape(3,3)
print(a_ufunc, a_ufunc[0][0], a_ufunc[0,0])
print(a_ufunc[:, 2]) # 每一行第三列的值
print(a_ufunc[1,:]) #第2行的所有值
print(a_ufunc[-1])  # 即a_ufunc[-1,:]， 倒数一行所有值

# 点...的用法
print(a_ufunc[...,1]) #即a_ufunc[:,1]  所有第二个值组成的ndarry

[0 1 2] [1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[[0 1 2]
 [3 4 5]
 [6 7 8]] 0 0
[2 5 8]
[3 4 5]
[6 7 8]
[1 4 7]


### 4. 形状操作
#### 4.1 更改数组的形状
+ shape、reshape、resize、ravel
    + reshape函数改变参数形状并返回它，而resize函数改变数组自身
    + **resize函数对本身的改变不限制原本的大小**，不够会自动填0
    + reshape、ravel新生成的数组和原数组共用一个内存，change时会互相影响，但id不同

In [35]:
from numpy import *
a_shape = floor(10*random.random((3,4)))
print(a_shape)
a_shape.shape = (6,2)
print(a_shape)
print(a_shape.reshape(3,4), a_shape)
print(a_shape.ravel())  # 转换成一个一维数组

a_shape.resize((5,3)) #改变a_shape自身,并且不限制原本元素
print(a_shape)  

[[9. 9. 8. 2.]
 [5. 6. 9. 2.]
 [9. 1. 6. 0.]]
[[9. 9.]
 [8. 2.]
 [5. 6.]
 [9. 2.]
 [9. 1.]
 [6. 0.]]
[[9. 9. 8. 2.]
 [5. 6. 9. 2.]
 [9. 1. 6. 0.]] [[9. 9.]
 [8. 2.]
 [5. 6.]
 [9. 2.]
 [9. 1.]
 [6. 0.]]
[9. 9. 8. 2. 5. 6. 9. 2. 9. 1. 6. 0.]
[[9. 9. 8.]
 [2. 5. 6.]
 [9. 2. 9.]
 [1. 6. 0.]
 [0. 0. 0.]]


In [76]:
##test_reshape reshape新生成的数组和原来的数组公用一个内存，会互相影响
test_shape = arange(12).reshape(3,4)
test_change = test_shape.reshape(2,6)
print(test_shape, test_change)

test_change[0][0] = 111   #只改变test_change的第一个值
print(test_shape, test_change) #发现test_shape原来的值也变了
print(id(test_shape), id(test_change))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[111   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]] [[111   1   2   3   4   5]
 [  6   7   8   9  10  11]]
140343276324464 140343276404784


In [30]:
## test_ravel ravel新生成的数组和原来的数组公用一个内存，会互相影响
test_ravel = test_shape.ravel()
print(test_ravel, test_shape)
test_ravel[0] = 222 # 只改变
print(test_ravel, test_shape)

[111   1   2   3   4   5   6   7   8   9  10  11] [[111   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[222   1   2   3   4   5   6   7   8   9  10  11] [[222   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


#### 4.2 组合（stack）不同的数组
+ vstack,hstack,column_stack,row_stack,c_[],r_[]
    + vstack：组合相同列 成为一个新数组，和原数组不占用同一内存
    + hstack：组合相同行 成为一个新数组，和原数组不占用同一内存
    + r_[] 和 c_[] 对创建沿着一个方向组合的数很有用，它们允许范围符号(:)

In [64]:
a_stack = arange(4).reshape((2,2))
b_stack = arange(6).reshape((2,3))
c_stack = arange(4).reshape((2,2))
vstack((a_stack, c_stack)) #vstack 只能组合列相同数组
hstack((a_stack, b_stack)) #hastck 只能组合行相同数组
column_stack((array([1,2,3]),array([4,5,6]))) #a中元素作为列展开
column_stack((a_stack, c_stack))
row_stack((array([1,2,3]),array([4,5,6]))) #a中元素作为行展开
row_stack((a_stack, c_stack))
r_[0:4,2,3]
c_[:3, [1,2,3]]

array([[0, 1],
       [1, 2],
       [2, 3]])

#### 4.3 数组分隔（split）
+ hsplit,vsplit
    + hsplit: 按照列分割
    + vsplit: 按照行分割

In [70]:
a_split = arange(4).reshape((2,2))
hsplit(a_split, 2) #分成两块
hsplit(a_split, (0,1)) #分割第1到第2列
vsplit(a_split, 2)

[array([[0, 1]]), array([[2, 3]])]

#### 4.4 复制和视图
+ '=' 对象的引用 ， a,b指向同一个地址空间
+ 视图：a.view()  地址不同，但指向同一个内存数据，数据变会跟着变
+ 深复制 .copy()  相当于deep copy(注意:这里和copy.copy()不同) 

In [79]:
a_ori = arange(4).reshape(2,2)
a_view = a_ori.view()
print(id(a_ori), id(a_view))
print(a_ori, a_view)
a_view[0][0] = 111
print(a_view, a_ori)  #只改变view的数据，都变化

140343276324624 140343276325584
[[0 1]
 [2 3]] [[0 1]
 [2 3]]
[[111   1]
 [  2   3]] [[111   1]
 [  2   3]]


In [88]:
#numpy 的copy
a_copy = a_ori.copy()
print(id(a_copy), id(a_ori))
a_copy[0][0] = 222
print(a_copy, a_ori)

140343276270576 140343276324624
[[222   1]
 [  2   3]] [[111   1]
 [  2   3]]
